name: Checkout and deploy

on: push

env:
  RUNS_ON: [self-hosted, sangsu-102]

jobs:
  checkout:
    name: 'Checkout'
    runs-on: ${{ RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'

  install_dependancy:
    name: 'Install dependancy'
    needs: [checkout]
    runs-on: $RUNS_ON
    steps:
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - run: npm cache verify
      - run: npm ci

  deploy:
    name: 'Deploy'
    needs: [checkout, install_dependancy]
    runs-on: $RUNS_ON
    steps:
      - run: ./start.sh
